# docker-compose.yml
#version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: dojolab-portal
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Variables de entorno que se pueden sobrescribir
      - VITE_DIRECTUS_URL=${VITE_DIRECTUS_URL:-https://api.thedojolab.com}
      - VITE_APP_NAME=${VITE_APP_NAME:-The Dojo Lab Dashboard}
      - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
      - VITE_DEV_MODE=${VITE_DEV_MODE:-false}
      - VITE_MAINTENANCE_ALLOWED_IPS=${VITE_MAINTENANCE_ALLOWED_IPS:-127.0.0.1,localhost}
    networks:
      - dojolab-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'

networks:
  dojolab-network:
    driver: bridge
    name: dojolab-network